"""create initial schema

Revision ID: 167f3a9d2fff
Revises:
Create Date: 2026-06-14 23:04:36.259783
"""

# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "167f3a9d2fff"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    op.create_table(
        "active_copy_wallets",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("wallet_address", sa.Text(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("desired_rank", sa.Integer(), nullable=True),
        sa.Column("score", sa.Numeric(), nullable=False),
        sa.Column(
            "activated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "has_realtime_slot", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("blocked_by_wallet_address", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('active', 'exit_only', 'promotion_pending', 'inactive')",
            name="ck_active_copy_wallets_status",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wallet_address"),
    )
    op.create_index(
        "ix_active_copy_wallets_has_realtime_slot",
        "active_copy_wallets",
        ["has_realtime_slot"],
        unique=False,
    )
    op.create_index(
        "ix_active_copy_wallets_status_rank",
        "active_copy_wallets",
        ["status", "rank"],
        unique=False,
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_logs_action_created", "audit_logs", ["action", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_logs_actor_created", "audit_logs", ["actor", "created_at"], unique=False
    )
    op.create_table(
        "copy_signals",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_wallet", sa.Text(), nullable=False),
        sa.Column("coin", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("side", sa.Text(), nullable=True),
        sa.Column("source_price", sa.Numeric(), nullable=True),
        sa.Column("observed_price", sa.Numeric(), nullable=True),
        sa.Column("price_drift_pct", sa.Numeric(), nullable=True),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("skip_reason", sa.Text(), nullable=True),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("raw_event_id", sa.UUID(), nullable=True),
        sa.Column("source_timestamp_ms", sa.BigInteger(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decision_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action in ('open', 'add', 'reduce', 'close', 'flip', 'unknown')",
            name="ck_copy_signals_action",
        ),
        sa.CheckConstraint(
            "decision in ('copy', 'skip', 'exit', 'observe')", name="ck_copy_signals_decision"
        ),
        sa.CheckConstraint(
            "mode in ('monitor', 'paper', 'live_small', 'full_live')", name="ck_copy_signals_mode"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_copy_signals_decision_created", "copy_signals", ["decision", "created_at"], unique=False
    )
    op.create_index(
        "ix_copy_signals_source_created",
        "copy_signals",
        ["source_wallet", "created_at"],
        unique=False,
    )
    op.create_table(
        "copy_trades",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("source_wallet", sa.Text(), nullable=False),
        sa.Column("coin", sa.Text(), nullable=False),
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("source_entry_price", sa.Numeric(), nullable=True),
        sa.Column("our_entry_price", sa.Numeric(), nullable=True),
        sa.Column("source_exit_price", sa.Numeric(), nullable=True),
        sa.Column("our_exit_price", sa.Numeric(), nullable=True),
        sa.Column("size_usd", sa.Numeric(), nullable=False),
        sa.Column("risk_usd", sa.Numeric(), nullable=True),
        sa.Column("pnl_usd", sa.Numeric(), nullable=True),
        sa.Column("pnl_pct", sa.Numeric(), nullable=True),
        sa.Column("entry_signal_id", sa.UUID(), nullable=True),
        sa.Column("exit_signal_id", sa.UUID(), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mode in ('paper', 'live_small', 'full_live')", name="ck_copy_trades_mode"
        ),
        sa.CheckConstraint("side in ('long', 'short')", name="ck_copy_trades_side"),
        sa.CheckConstraint(
            "status in ('open', 'closing', 'closed', 'cancelled', 'error')",
            name="ck_copy_trades_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_copy_trades_coin_status", "copy_trades", ["coin", "status"], unique=False)
    op.create_index(
        "ix_copy_trades_source_status", "copy_trades", ["source_wallet", "status"], unique=False
    )
    op.create_index(
        "ix_copy_trades_status_opened", "copy_trades", ["status", "opened_at"], unique=False
    )
    op.create_table(
        "risk_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity in ('info', 'warning', 'critical')", name="ck_risk_events_severity"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_risk_events_severity_created", "risk_events", ["severity", "created_at"], unique=False
    )
    op.create_index(
        "ix_risk_events_type_created", "risk_events", ["event_type", "created_at"], unique=False
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    settings_table = sa.table(
        "settings",
        sa.column("key", sa.Text()),
        sa.column("value", postgresql.JSONB()),
    )
    op.bulk_insert(
        settings_table,
        [
            {
                "key": "system_mode",
                "value": {
                    "paperTradingEnabled": True,
                    "liveTradingEnabled": False,
                },
            },
            {
                "key": "active_set",
                "value": {
                    "activeCopyWallets": 10,
                    "activeSetRefreshMinutes": 15,
                    "minPromotionMargin": 5,
                    "minActiveDurationHours": 2,
                    "cooldownAfterDemotionHours": 6,
                    "maxRealtimeWallets": 10,
                },
            },
            {
                "key": "risk",
                "value": {
                    "riskPerTradePct": 0.20,
                    "maxOpenTrades": 10,
                    "maxOpenTradesPerWallet": 2,
                    "maxDailyLossPct": 2.00,
                    "maxWeeklyLossPct": 5.00,
                    "maxPriceDriftPct": 0.15,
                    "maxPerWalletExposurePct": 10.00,
                    "maxPerCoinExposurePct": 20.00,
                    "maxTotalExposurePct": 30.00,
                    "emergencyStopPct": 0.60,
                    "copyAdds": False,
                    "copyPartialCloses": True,
                    "copyFlips": False,
                },
            },
        ],
    )
    op.create_table(
        "source_trade_links",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_wallet", sa.Text(), nullable=False),
        sa.Column("source_fill_id", sa.Text(), nullable=True),
        sa.Column("copy_trade_id", sa.UUID(), nullable=False),
        sa.Column("coin", sa.Text(), nullable=False),
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("link_type", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "link_type in ('entry', 'add', 'reduce', 'close', 'flip')",
            name="ck_source_trade_links_link_type",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_source_trade_links_copy_trade_id", "source_trade_links", ["copy_trade_id"], unique=False
    )
    op.create_index(
        "ix_source_trade_links_source_fill",
        "source_trade_links",
        ["source_wallet", "source_fill_id"],
        unique=False,
    )
    op.create_table(
        "wallet_fills",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("wallet_address", sa.Text(), nullable=False),
        sa.Column("external_fill_id", sa.Text(), nullable=True),
        sa.Column("coin", sa.Text(), nullable=False),
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("size", sa.Numeric(), nullable=False),
        sa.Column("notional_usd", sa.Numeric(), nullable=True),
        sa.Column("fee_usd", sa.Numeric(), nullable=True),
        sa.Column("pnl_usd", sa.Numeric(), nullable=True),
        sa.Column("timestamp_ms", sa.BigInteger(), nullable=False),
        sa.Column("source_timestamp_ms", sa.BigInteger(), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingest_latency_ms", sa.Integer(), nullable=True),
        sa.Column("is_snapshot", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("raw_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("side in ('buy', 'sell', 'long', 'short')", name="ck_wallet_fills_side"),
    )
    op.create_index(
        "ux_wallet_fills_wallet_external",
        "wallet_fills",
        ["wallet_address", "external_fill_id"],
        unique=True,
    )
    op.create_table(
        "wallet_positions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("wallet_address", sa.Text(), nullable=False),
        sa.Column("coin", sa.Text(), nullable=False),
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("size", sa.Numeric(), nullable=False),
        sa.Column("entry_price", sa.Numeric(), nullable=True),
        sa.Column("notional_usd", sa.Numeric(), nullable=True),
        sa.Column("unrealized_pnl_usd", sa.Numeric(), nullable=True),
        sa.Column("liquidation_price", sa.Numeric(), nullable=True),
        sa.Column("raw_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("side in ('long', 'short', 'flat')", name="ck_wallet_positions_side"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_wallet_positions_updated_at", "wallet_positions", ["updated_at"], unique=False
    )
    op.create_index(
        "ux_wallet_positions_wallet_coin",
        "wallet_positions",
        ["wallet_address", "coin"],
        unique=True,
    )
    op.create_table(
        "wallet_score_snapshots",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("wallet_address", sa.Text(), nullable=False),
        sa.Column("score", sa.Numeric(), nullable=False),
        sa.Column("score_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_wallet_score_snapshots_wallet_created",
        "wallet_score_snapshots",
        ["wallet_address", "created_at"],
        unique=False,
    )
    op.create_table(
        "wallet_scores",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("wallet_address", sa.Text(), nullable=False),
        sa.Column("score", sa.Numeric(), server_default=sa.text("0"), nullable=False),
        sa.Column("pnl_score", sa.Numeric(), server_default=sa.text("0"), nullable=False),
        sa.Column("copyability_score", sa.Numeric(), server_default=sa.text("0"), nullable=False),
        sa.Column("risk_score", sa.Numeric(), server_default=sa.text("0"), nullable=False),
        sa.Column("consistency_score", sa.Numeric(), server_default=sa.text("0"), nullable=False),
        sa.Column("recency_score", sa.Numeric(), server_default=sa.text("0"), nullable=False),
        sa.Column("penalty_score", sa.Numeric(), server_default=sa.text("0"), nullable=False),
        sa.Column("copyable_pnl_usd", sa.Numeric(), server_default=sa.text("0"), nullable=False),
        sa.Column("win_rate", sa.Numeric(), nullable=True),
        sa.Column("profit_factor", sa.Numeric(), nullable=True),
        sa.Column("max_drawdown_pct", sa.Numeric(), nullable=True),
        sa.Column("trade_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_24h_score", sa.Numeric(), nullable=True),
        sa.Column("last_7d_score", sa.Numeric(), nullable=True),
        sa.Column("last_30d_score", sa.Numeric(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wallet_address"),
    )
    op.create_index("ix_wallet_scores_score", "wallet_scores", ["score"], unique=False)
    op.create_index("ix_wallet_scores_updated_at", "wallet_scores", ["updated_at"], unique=False)
    op.create_table(
        "watched_wallets",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("eligible", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("copy_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("polling_tier", sa.Text(), server_default=sa.text("'pool'"), nullable=False),
        sa.Column("cooldown_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_polled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_fill_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "polling_tier in ('pool', 'candidate', 'active', 'exit_only', 'cooldown')",
            name="ck_watched_wallets_polling_tier",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
    )
    op.create_index(
        "ix_watched_wallets_enabled_eligible",
        "watched_wallets",
        ["enabled", "eligible"],
        unique=False,
    )
    op.create_index(
        "ix_watched_wallets_polling_tier", "watched_wallets", ["polling_tier"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_watched_wallets_polling_tier", table_name="watched_wallets")
    op.drop_index("ix_watched_wallets_enabled_eligible", table_name="watched_wallets")
    op.drop_table("watched_wallets")
    op.drop_index("ix_wallet_scores_updated_at", table_name="wallet_scores")
    op.drop_index("ix_wallet_scores_score", table_name="wallet_scores")
    op.drop_table("wallet_scores")
    op.drop_index("ix_wallet_score_snapshots_wallet_created", table_name="wallet_score_snapshots")
    op.drop_table("wallet_score_snapshots")
    op.drop_index("ux_wallet_positions_wallet_coin", table_name="wallet_positions")
    op.drop_index("ix_wallet_positions_updated_at", table_name="wallet_positions")
    op.drop_table("wallet_positions")
    op.drop_index("ux_wallet_fills_wallet_external", table_name="wallet_fills")
    op.drop_table("wallet_fills")
    op.drop_index("ix_source_trade_links_source_fill", table_name="source_trade_links")
    op.drop_index("ix_source_trade_links_copy_trade_id", table_name="source_trade_links")
    op.drop_table("source_trade_links")
    op.drop_table("settings")
    op.drop_index("ix_risk_events_type_created", table_name="risk_events")
    op.drop_index("ix_risk_events_severity_created", table_name="risk_events")
    op.drop_table("risk_events")
    op.drop_index("ix_copy_trades_status_opened", table_name="copy_trades")
    op.drop_index("ix_copy_trades_source_status", table_name="copy_trades")
    op.drop_index("ix_copy_trades_coin_status", table_name="copy_trades")
    op.drop_table("copy_trades")
    op.drop_index("ix_copy_signals_source_created", table_name="copy_signals")
    op.drop_index("ix_copy_signals_decision_created", table_name="copy_signals")
    op.drop_table("copy_signals")
    op.drop_index("ix_audit_logs_actor_created", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_active_copy_wallets_status_rank", table_name="active_copy_wallets")
    op.drop_index("ix_active_copy_wallets_has_realtime_slot", table_name="active_copy_wallets")
    op.drop_table("active_copy_wallets")
    # ### end Alembic commands ###
